server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # Resolución DNS dinámica (evita cachear la IP del backend)
    resolver 127.0.0.11 valid=10s;
    set $backend http://app:8000;

    # Sirve el frontend estático
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Redirige /api/* al backend Laravel
    location /api/ {
        proxy_pass $backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # Redirige /stats/* al microservicio Python
    set $stats http://stats:5000;
    location /stats/ {
        proxy_pass $stats;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}